# Generated by Django 5.2.3 on 2025-07-01 14:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='coment',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Comentario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcción'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='duracion_horas',
            field=models.IntegerField(verbose_name='Duración de horas'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='foto', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de editado'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('coment', ckeditor.fields.RichTextField(verbose_name='Comentario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Cursos')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created'],
            },
        ),
    ]
